id: openelis
canonical: http://digi-uw.github.io/openelis-global-ig
version: 0.1.0
name: OpenELISImplementationGuide
title: OpenELIS GLOBAL2 Implementation Guide
status: draft
publisher: DIGI-UW
# contact:
  # - name: DIGI-UW
    # telecom:
      # - system: url
        # value:  https://digi-uw.github.io/openelis-global2-fhir-ig
description: An Implementation Guide covering the OpenELIS GLOBAL2 implementation of FHIR
license: CC-BY-SA-4.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-license: true
  apply-contact: true
copyrightYear: 2021+
releaseLabel: ci-build
