id: openelis
canonical: http://i-tech-uw.github.io/openelis-global-ig
version: 0.1.0
name: OpenELISImplementationGuide
title: OpenELIS GLOBAL2 Implementation Guide
status: draft
publisher: I-TECH-UW
contact:
  - name: I-TECH-UW
    telecom:
      - system: url
        value:  www.github.com/i-tech-uw
description: An Implementation Guide covering the OpenELIS GLOBAL2 implementation of FHIR
license: CC-BY-SA-4.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-license: true
  apply-contact: true
copyrightYear: 2021+
releaseLabel: ci-build
